import React, { Component } from "react";
import Navigation from "../components/Navigation.jsx";
import "../styles/aviso.scss";

export default class Aviso extends Component {

  render() {
    return (
      <>
        <Navigation />
        <div className="terminosContenedor">
          <h1 className="bold">AVISO DE PRIVACIDAD INTEGRAL</h1>
          <p className="bold">Responsable</p>
          <p>SAFETI (en adelante, y de forma conjunta el “Responsable”) con domicilio convencional ubicado en Guayana Holandesa 309 Vista Hermosa. Monterrey NL 64620, correo electrónico admin@safeti.mx,, estamos conscientes que usted como visitante de nuestras oficinas y/o sitio web, consumidor o potencial consumidor de nuestros productos y/o servicios tiene derecho a conocer qué información recabamos de usted y nuestras prácticas en relación con dicha información.</p>
          <p>Las condiciones contenidas en el presente son aplicables a la información que se recaba a nombre de y por el Responsable o cualquiera de sus empresas filiales o subsidiarias, por cualquier medio, incluyendo a través de o cualquier sitio web operado por el Responsable.</p>
          <p className="bold">Datos Personales</p>
          <p>Los datos personales que puede llegar a recabar el Responsable de forma directa o indirecta consisten en los siguientes: Los datos personales considerados como de identificación son todos los relativos a la identificación de la persona (nombre completo, dirección, teléfonos fijo y/o celular, empresa para la cual labora, huellas digitales, fecha de nacimiento, nacionalidad, lugar de nacimiento, ocupación y/o sus familiares directos). Nos comprometemos a que todos los datos obtenidos serán tratados bajo las más estrictas medidas de seguridad que garanticen su confidencialidad.</p>
          <p className="bold">Finalidades</p>
          <p>La finalidad principal para las que recabamos sus datos tiene por objeto ofrecer servicios de seguridad, backup, mantenimiento, administración e inventario de equipo de cómputo, cumpliendo con los estándares mediante los procesos internos para asegurar la calidad y seguridad del cliente en nuestras instalaciones.</p>
          <p>Las finalidades secundarias para las que recabamos sus datos son: facturación, cobranza, informarle sobre nuevos productos, servicios o cambios en los mismos, mensajes promocionales; evaluar la calidad del servicio; cumplir con las obligaciones derivadas de la prestación del servicio; cumplir con la legislación aplicable vigente; contestar requerimientos de información de cualquier autoridad, ya sea por investigaciones, estadísticas o reportes normativos; atender a sus comentarios relacionados con la prestación de servicios; enviar avisos e información de nuestros servicios; y coadyuvar con el proceso de mejora continua.</p>
          <p className="bold">Transferencias y Encargados de Datos Personales</p>
          <p>Asimismo, le informamos que sus datos personales podrán ser transferidos a terceros y podrán ser compartidos a encargados para su tratamiento dentro y fuera del país, por personas distintas al Responsable, quien girará las instrucciones para su tratamiento. En ese sentido, su información puede ser transferida o compartida con (i) Diversos profesionales, técnicos y auxiliares, así como otros entes privados por cuestión de servicios subrogados en relación con la atención del cliente; (ii) Administradoras de programas de lealtad; (iii) Socios comerciales del Responsable, con la finalidad de que estos administren y operen servicios complementarios a los del Responsable; (iv) Sociedades o terceros que operen en forma conjunta con el Responsable algún producto, servicio o cualquier software o infraestructura informática que sirva como plataforma para la realización de operaciones o servicios; (v) Terceros prestadores de servicios o vendedores de productos necesarios para la operación de la responsable, así como comisionistas que realicen operaciones o brinden servicios a la responsable que esta pueda realizar de acuerdo con la legislación vigente y sus estatutos sociales, como son, entre otros, comisionistas, procesadores de datos, empresas de envío de material de marketing, empresas de mensajería, de seguridad, transporte de valores, agencias de publicidad, guarda de información, con el propósito de que estos asistan en la realización de las finalidades previstas en este aviso de privacidad; (vi) Profesionistas, asesores o consultores externos, para efecto de la administración de operaciones de venta, servicios y de los demás actos que la responsable pueda realizar de conformidad con la legislación vigente y sus estatutos sociales, así como para la defensa de sus intereses ante cualquier controversia legal que surja con motivo de dichas operaciones y servicios, tales como agencias de cobranza, auditores externos, legales, contables, etc.; y (vii) Todas aquellas dependencias gubernamentales y/o judiciales que por ministerio de ley soliciten y/o requieran de la responsable datos personales de sus clientes y/o familiares, necesarias para el cumplimiento de diversas legislaciones.</p>
          <p>Si usted no manifiesta su oposición para que sus datos personales sean transferidos, se entenderá que ha otorgado su consentimiento para ello.</p>
          <p>El Responsable informa que todos los contratos de prestación de servicios con terceros que impliquen el tratamiento de su información personal a nombre y por cuenta del Responsable incluirán una cláusula garantizando que otorgan el nivel de protección de datos personales, mediante el cual se constituyan encargados en términos del párrafo anterior. En cualquier caso, todo manejo de datos personales se realizará dando cumplimiento a la Ley Federal de Protección de Datos Personales en Posesión de Particulares (en adelante la “Ley”) y su Reglamento.</p>
          <p>La información que proporcione deberá ser veraz y completa. Por lo que queda bajo su responsabilidad la veracidad de los datos proporcionados y en ningún caso el Responsable será responsable a este respecto.</p>
          <p className="bold">Ejercicio de Derechos ARCO</p>
          <p>En el momento que lo estime oportuno podrá ejercer sus derechos ARCO (acceso, rectificación, cancelación y oposición) sobre el tratamiento de los datos personales proporcionados, así como revocar el consentimiento otorgado en este documento, por lo cual deberá ponerse en contacto con nosotros a través del correo electrónico admin@safeti.mx; el procedimiento y requisitos que deberá contener su solicitud de conformidad con lo dispuesto en la Ley y su Reglamento, son los siguientes:</p>
          <p>(1) Nombre y Domicilio, si no se incluye la dirección se dará por no recibida la solicitud. (2) El documento que acredite su identidad o la personalidad de su representante (copia de identificación oficial vigente.) El representante deberá acreditar la identidad del titular, identidad del representante, y sus facultades de representación mediante instrumento público o carta poder firmada ante dos testigos, o declaración en comparecencia personal del titular; (3) La descripción clara y precisa de los datos personales a los que desea acceder, rectificar, cancelar u oponerse; (4) Descripción de otros elementos que faciliten la localización de sus datos personales (sitio Web, Sucursal).Los documentos deberán ser escaneados y adjuntados al correo electrónico para verificar la veracidad de los mismos.</p>
          <p>Para conocer el procedimiento, requisitos y plazos del ejercicio de los derechos ARCO puedes ponerte en contacto al correo electrónico admin@safeti.mx.</p>
          <p className="bold">Video de Vigilancia</p>
          <p>Le informamos que usted está siendo grabado por las cámaras de seguridad del Responsable. Los sonidos e imágenes serán utilizados para brindarle seguridad a usted y a los demás visitantes.</p>
          <p>El Responsable ha adoptado los niveles de seguridad de protección de datos personales legalmente requeridos por la Ley y su Reglamento, bajo los principios de licitud, calidad, consentimiento, información, finalidad, lealtad, proporcionalidad y responsabilidad. Todo esto bajo estrictas reglas de seguridad, confidencialidad y consistencia de información.</p>
          <p>Hacemos de su conocimiento que sus datos personales serán resguardados bajo estrictas medidas de seguridad administrativas, técnicas y físicas las cuales han sido implementadas con el objeto de proteger sus datos personales contra daño, perdida, alteración, destrucción o el uso o acceso o tratamiento no autorizado.</p>
          <p className="bold">Modificaciones al Aviso de Privacidad</p>
          <p>El Responsable se reserva el derecho de efectuar en cualquier momento modificaciones o actualizaciones al presente aviso de privacidad, para la atención de novedades legislativas o jurisprudenciales, políticas internas, nuevos requerimientos para la prestación u ofrecimiento de nuestros servicios y prácticas del mercado, cualquier modificación al Aviso de Privacidad estará disponible a través de nuestro portal Web; sección “aviso de privacidad”.</p>
          <p>nEl presente Aviso de Privacidad ha sido modificado el día dos del mes de mayo del año dos mil veinte.</p>
        </div>
        <footer>
          <h5>©Safeti 2020 – Aviso de privacidad</h5>
        </footer>
      </>
    );
  }
}
